#!/usr/bin/env sh
set -eu
while read -r local_ref local_oid remote_ref remote_oid; do
    case "$local_oid" in
        0000000000000000000000000000000000000000) continue ;;
    esac
    python3 script/check_repository_privacy.py --history "$local_oid"
done
